1. Write a NumPy program to test whether none of the elements of a given array is zero.

In [46]:
import numpy as np
a = np.array([[1, 3, 0], [2, 4, 5]])
print(a.any() != 0)

True


2. Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [47]:
a = np.array([[1, 3, 0], [2, 4, 5]])
b = np.array([[5, 4, 1], [1, 2, 5]])
print( (a == b).any())

True


3. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given

In [72]:
x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])
print(np.allclose(x, y))

True


4. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [48]:
a = np.full(10, 0)
b = np.full(10, 1)
c = np.full(10, 5)
d = np.array((a, b, c))
print(d)

[[0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [5 5 5 5 5 5 5 5 5 5]]


5. Write a NumPy program to create an array of the integers from 30 to70.

In [49]:
print(np.linspace(30, 70, 41))

[30. 31. 32. 33. 34. 35. 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47.
 48. 49. 50. 51. 52. 53. 54. 55. 56. 57. 58. 59. 60. 61. 62. 63. 64. 65.
 66. 67. 68. 69. 70.]


6. Write a NumPy program to create a 3x3 identity matrix

In [50]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


7. Write a NumPy program to generate a random number between 0 and 1

In [51]:
print(np.random.rand())

0.843948387112048


8. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution

In [52]:
print(np.random.randn(15))

[-0.82202847  1.00216097  0.49430377 -1.33507107 -0.04398699  1.16336897
 -0.62795184 -0.01855006 -0.83735881 -1.55198778 -1.58809937 -0.16997917
 -1.64227445  0.82226483 -0.06802215]


9. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

In [53]:
print(np.linspace(16, 54, 39))

[16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33.
 34. 35. 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51.
 52. 53. 54.]


10. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10

In [54]:
print(np.random.randint(0, 11, 5))

[3 2 1 1 7]


11. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [55]:
a = np.ones((10, 10))
a[1:-1, 1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


12. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [58]:
print(np.diag([1, 2, 3, 4, 5]))

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


13. Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal

In [62]:
a = np.zeros((4, 4))
a[::2, 1::2] = 1
a[1::2, ::2] = 1
print(a)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


14. Write a NumPy program to save two given arrays into a single file in compressed format (.npz format) and load it.

In [65]:

x = np.arange(10)
y = np.arange(11, 20)

np.savez('temp_arra.npz', x=x, y=y)

with np.load('temp_arra.npz') as data:
    x2 = data['x']
    y2 = data['y']
    print(x2)
    print(y2)

[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]


15. Write a NumPy program to create a one-dimensional array of forty pseudo-randomly generated values. Select

In [69]:
print(np.random.rand(40))

[0.54758616 0.819287   0.19894754 0.8568503  0.35165264 0.75464769
 0.29596171 0.88393648 0.32551164 0.1650159  0.39252924 0.09346037
 0.82110566 0.15115202 0.38411445 0.94426071 0.98762547 0.45630455
 0.82612284 0.25137413 0.59737165 0.90283176 0.53455795 0.59020136
 0.03928177 0.35718176 0.07961309 0.30545992 0.33071931 0.7738303
 0.03995921 0.42949218 0.31492687 0.63649114 0.34634715 0.04309736
 0.87991517 0.76324059 0.87809664 0.41750914]


16. Write a NumPy program to extract all numbers from a given array which are less and greater than a specified number.

In [71]:
a= np.array([2, 6, 48, 21, 51, 26, 35, 24, 15, 29, 13, 8, 19])
print(a[a>15])

[48 21 51 26 35 24 29 19]
